# Generated by Django 3.0.3 on 2020-03-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200322_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='Це поле буде заповнено автоматично', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='users.Client'),
        ),
    ]
